# Generated by Django 4.1 on 2022-09-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_task_detail_alter_task_level_alter_task_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Department',
            new_name='department',
        ),
    ]
